-- 25 entries from real May/June 2026 published research
-- Sources: Gallup 2026, Talent Strategy Group 2026, Deloitte 2026, Gartner 2026, PE Talent surveys
-- Run in Neon SQL editor

INSERT INTO research_entries
  (finding, context, source_firm, report_name, published_year,
   topics, audience_fit, incompass_relevance, opportunity_type,
   strength_rating, incompass_angle, ai_generated)
VALUES

-- GALLUP STATE OF THE GLOBAL WORKPLACE 2026
(
  'Employee engagement dropped 20% from its 2023 peak — the steepest decline Gallup has recorded, driven primarily by a collapse in manager engagement.',
  'Gallup State of the Global Workplace 2026, surveying 141,444 employed respondents across 140+ countries and territories.',
  'Gallup',
  'State of the Global Workplace 2026: The Human Side of the AI Revolution',
  2026,
  ARRAY['engagement','leadership_effectiveness'],
  ARRAY['c_suite','hr','pe_firms'],
  'direct',
  'validates_product',
  5,
  'A 20% engagement drop in three years represents a structural crisis, not a cyclical dip. For Incompass, this is the opening stat in every C-suite conversation: if manager quality is the primary driver of engagement — and engagement drives productivity and retention — then calibrating and developing managers isn''t an HR expense, it''s the single highest-ROI investment available.',
  false
),
(
  'Manager engagement declined at nearly 3x the rate of overall employee engagement over the past three years — making manager quality the #1 driver of the global engagement crisis.',
  'Gallup State of the Global Workplace 2026. Manager engagement specifically tracked as a leading indicator before broader workforce disengagement.',
  'Gallup',
  'State of the Global Workplace 2026: The Human Side of the AI Revolution',
  2026,
  ARRAY['leadership_effectiveness','engagement'],
  ARRAY['c_suite','hr'],
  'direct',
  'validates_product',
  5,
  'Manager disengagement at 3x the employee rate points directly to the broken feedback and calibration loop. Managers who receive unclear performance expectations or feel their own performance is evaluated unfairly disengage — and their teams follow. Incompass''s 360 feedback and calibration tools are precisely the intervention this data calls for.',
  false
),
(
  'Employees whose managers actively support AI use are 8.7x more likely to report that AI has meaningfully transformed their work — far outpacing the impact of any technical integration factor.',
  'Gallup State of the Global Workplace 2026. Analyzed AI transformation outcomes by manager behavior, technical access, and organizational policy.',
  'Gallup',
  'State of the Global Workplace 2026: The Human Side of the AI Revolution',
  2026,
  ARRAY['leadership_effectiveness','workforce_performance'],
  ARRAY['c_suite','hr'],
  'adjacent',
  'new_use_case',
  4,
  'The 8.7x multiplier on manager-led AI adoption reinforces Incompass''s positioning: leadership quality is the highest-leverage variable in organizational transformation. If your managers aren''t calibrated and engaged, AI investments return nothing. This opens a conversation about Incompass as the prerequisite to any AI workforce strategy.',
  false
),

-- 2026 PERFORMANCE MANAGEMENT REPORT (TALENT STRATEGY GROUP — 250+ orgs)
(
  '84.7% of organizations hold performance calibration meetings — yet only 17.9% mandate any calibration or feedback training for managers conducting them.',
  '2026 Performance Management Report by Talent Strategy Group, drawing on data from 250+ organizations across industries, sizes, and geographies. Published February 2026.',
  'Talent Strategy Group',
  '2026 Performance Management Report',
  2026,
  ARRAY['measurement','bias'],
  ARRAY['hr','c_suite'],
  'direct',
  'validates_product',
  5,
  'Nearly every organization calibrates, but almost none train managers how to do it. This is exactly the gap Incompass fills: structured, technology-supported calibration that removes the dependence on manager skill or bias. The stat makes the case that calibration without infrastructure is theater — and Incompass is the infrastructure.',
  false
),
(
  '47% of organizations encourage 3–4 formal feedback conversations per cycle, but in practice 68.5% report that only 1–2 conversations actually occur — a 21-point execution gap.',
  '2026 Performance Management Report, Talent Strategy Group. Gap measured between stated policy and actual manager behavior across 250+ organizations.',
  'Talent Strategy Group',
  '2026 Performance Management Report',
  2026,
  ARRAY['measurement','engagement'],
  ARRAY['hr','c_suite'],
  'direct',
  'validates_product',
  4,
  'The 21-point gap between policy and practice is a systemic accountability failure — managers know what they should do but don''t do it. Incompass''s structured feedback tools create a trackable, accountable feedback cadence: not just enabling conversations but ensuring they happen and measuring their quality.',
  false
),
(
  '69.2% of organizations use NO AI in their performance reviewing process, and 88.7% use no AI in compensation decisions — despite AI being the most discussed topic in HR.',
  '2026 Performance Management Report, Talent Strategy Group, 250+ organizations surveyed in early 2026.',
  'Talent Strategy Group',
  '2026 Performance Management Report',
  2026,
  ARRAY['measurement','workforce_performance'],
  ARRAY['hr','c_suite'],
  'direct',
  'white_space',
  5,
  'The gap between AI hype and AI adoption in performance management is massive — 69% still doing reviews with zero AI support. Incompass is ahead of this curve: already deploying AI-assisted calibration and bias detection while competitors are still debating implementation. This is a first-mover advantage stat for Incompass sales conversations.',
  false
),
(
  '55.4% of organizations redesigned their performance management process within the past two years — yet show "no material differences in perceived process effectiveness" compared to those who didn''t.',
  '2026 Performance Management Report, Talent Strategy Group. Effectiveness measured by manager and employee perception surveys pre- and post-redesign.',
  'Talent Strategy Group',
  '2026 Performance Management Report',
  2026,
  ARRAY['measurement','workforce_performance'],
  ARRAY['hr','c_suite'],
  'direct',
  'validates_product',
  5,
  'More than half of organizations just overhauled their performance management — and it changed nothing. This is Incompass''s strongest competitive opening: process redesign alone doesn''t work. What drives effectiveness is the infrastructure underneath — standardized calibration, bias reduction, structured data — which is exactly what Incompass delivers.',
  false
),
(
  'Organizations running a single, unified performance management process for all employees show 17% higher effectiveness in improving individual performance and 19% higher effectiveness in distributing compensation fairly.',
  '2026 Performance Management Report, Talent Strategy Group, comparative analysis of organizations with unified vs. fragmented PM approaches.',
  'Talent Strategy Group',
  '2026 Performance Management Report',
  2026,
  ARRAY['measurement','talent_cost'],
  ARRAY['hr','c_suite'],
  'direct',
  'validates_product',
  4,
  'A 17–19% effectiveness gain from process standardization quantifies exactly what Incompass delivers: one consistent, bias-reduced calibration process across the entire organization. For CHROs, this is the ROI case for replacing fragmented manager-by-manager approaches with an Incompass-powered system.',
  false
),

-- DELOITTE 2026 GLOBAL HUMAN CAPITAL TRENDS (9,000+ across 89 countries)
(
  '7 in 10 business leaders say their primary competitive strategy over the next three years is to be fast and nimble — yet only 27% believe their organizations manage change effectively.',
  'Deloitte 2026 Global Human Capital Trends, surveying 9,000+ business and HR leaders across 89 countries in collaboration with Oxford Economics.',
  'Deloitte',
  '2026 Global Human Capital Trends',
  2026,
  ARRAY['workforce_performance','leadership_effectiveness'],
  ARRAY['c_suite','pe_firms'],
  'direct',
  'validates_product',
  4,
  'Speed is the strategy, but only 27% can execute on it. The constraint isn''t vision — it''s leadership quality and organizational agility. Incompass''s performance calibration and talent assessment tools give leadership teams the clear picture of who can lead at speed — and who is a drag on it.',
  false
),
(
  '59% of organizations take a technology-first approach to AI — yet those organizations are 1.6x more likely to fail to realize returns on their AI investments compared to human-centered approaches.',
  'Deloitte 2026 Global Human Capital Trends, 9,000+ respondents. AI ROI measured by whether investments exceeded financial expectations.',
  'Deloitte',
  '2026 Global Human Capital Trends',
  2026,
  ARRAY['workforce_performance','measurement'],
  ARRAY['c_suite','pe_firms'],
  'adjacent',
  'new_use_case',
  4,
  'AI without people strategy fails at 1.6x the rate — and Incompass is the people strategy layer. This reframes Incompass as the prerequisite to successful AI transformation: you need calibrated leadership, clear performance data, and bias-free talent decisions before AI can improve them. Use with PE firms investing in AI transformation at portcos.',
  false
),
(
  'One-third of workers experienced 15 or more major organizational changes in the past year alone — yet only 27% of organizations believe they manage change effectively, creating an execution debt.',
  'Deloitte 2026 Global Human Capital Trends, with supplemental worker surveys across 89 countries. Change fatigue identified as a leading driver of attrition and disengagement.',
  'Deloitte',
  '2026 Global Human Capital Trends',
  2026,
  ARRAY['engagement','workforce_performance'],
  ARRAY['c_suite','hr'],
  'adjacent',
  'validates_product',
  4,
  'Change fatigue at scale is a leadership execution problem. Organizations that can''t manage change effectively lose talent and momentum during the transitions that matter most — acquisitions, restructuring, growth phases. Incompass''s talent calibration tools help leaders identify who can carry the load and who needs support before the change hits.',
  false
),

-- GARTNER 2026
(
  'By 2027, 50% of enterprises without a people-centric AI strategy will lose their top AI talent to competitors who prioritize workforce enablement over basic adoption. (Gartner, May 2026)',
  'Gartner Global Labor Market Survey Q1 2026, 12,004 employees and managers across 40 countries. Published May 13, 2026.',
  'Gartner',
  'Gartner Predicts: People-Centric AI and Talent Retention, May 2026',
  2026,
  ARRAY['workforce_performance','talent_cost'],
  ARRAY['c_suite','pe_firms'],
  'adjacent',
  'new_use_case',
  4,
  'The warning that half of enterprises will lose top talent without a people-centric AI strategy opens the door for Incompass: a people-centric strategy requires knowing which people you have, how they perform, and where the gaps are. Incompass provides that foundation — making it a prerequisite to the AI talent retention strategy Gartner is prescribing.',
  false
),
(
  'Gartner identifies talent calibration and structured performance data as top priorities for CHROs in 2026, citing that ad-hoc calibration creates legal liability and pay inequity exposure.',
  'Gartner Top Future of Work Trends for CHROs 2026, published January 2026. Based on surveys of CHRO peer group and interviews.',
  'Gartner',
  'Top Future of Work Trends for CHROs 2026',
  2026,
  ARRAY['measurement','bias'],
  ARRAY['hr','c_suite'],
  'direct',
  'validates_product',
  4,
  'Gartner naming calibration as a CHRO priority — and framing ad-hoc calibration as a legal liability — gives Incompass a regulatory and risk-management angle, not just a performance angle. This is the conversation with General Counsel, CFO, and CHRO together: Incompass reduces legal exposure from inconsistent ratings.',
  false
),

-- PE TALENT TRENDS 2026
(
  'In 2026, demand for Chief Revenue Officers, Chief Commercial Officers, and Chief Growth Officers in PE-backed companies is outpacing CFO searches in multiple segments — a reversal of the past five years.',
  'Beecher Reagan PE Executive Talent Trends Newsletter 2026; Hunt Scanlon Media PE Talent Report 2026. Based on executive search activity data.',
  'Beecher Reagan / Hunt Scanlon',
  'Private Equity Executive Talent Trends 2026',
  2026,
  ARRAY['pe_specific','leadership_effectiveness'],
  ARRAY['pe_firms'],
  'direct',
  'new_buyer',
  4,
  'PE firms shifting from financial optimization to revenue growth means leadership assessment is expanding beyond the CFO to the full commercial C-suite. Incompass''s talent assessment tools are directly applicable here — helping PE firms evaluate CRO/CCO/CGO candidates with the same rigor they''d apply to a CFO search.',
  false
),
(
  'CEO transitions in PE-backed companies are accelerating in 2026, particularly in founder-led businesses entering the second half of their hold period — with most occurring without formal leadership assessment.',
  'Hunt Scanlon PE Executive Talent Report 2026 and Beecher Reagan 2026 newsletter. Transition timing data from executive search activity.',
  'Hunt Scanlon / Beecher Reagan',
  'Private Equity Executive Talent Trends 2026',
  2026,
  ARRAY['pe_specific','leadership_effectiveness'],
  ARRAY['pe_firms'],
  'direct',
  'white_space',
  5,
  'CEO transitions without formal assessment are the highest-risk, highest-cost talent event in any PE portfolio. Incompass''s talent assessment suite enables PE firms to conduct structured leadership evaluations before and during CEO transitions — reducing the risk of a costly mis-hire at the most critical moment in the hold period.',
  false
),
(
  '"Most PE value creation plans don''t fail on strategy or capital — they stall where execution actually happens, with people." — Beecher Reagan PE Talent Trends 2026.',
  'Direct quote from Beecher Reagan''s 2026 PE executive talent newsletter, describing the root cause of value creation failures across PE portfolios.',
  'Beecher Reagan',
  'Private Equity Executive Talent Trends 2026',
  2026,
  ARRAY['pe_specific','leadership_effectiveness'],
  ARRAY['pe_firms'],
  'direct',
  'validates_product',
  5,
  'This quote is Incompass''s thesis in a sentence. It belongs in the deck, on the website, in the first slide of every PE firm pitch. The problem Incompass solves isn''t strategy — it''s the measurement and calibration of the people executing strategy. Share this with operating partners who have lived this exact failure.',
  false
),
(
  'The Chief People Officer role in PE-backed companies is evolving from HR administration to a strategic growth function — responsible for leadership bench-building, acquisition integration, and executive retention.',
  'Hunt Scanlon and Beecher Reagan PE Talent 2026. CPO evolution tracked across 150+ PE-backed companies in professional services, tech, and business services.',
  'Hunt Scanlon / Beecher Reagan',
  'Private Equity Executive Talent Trends 2026',
  2026,
  ARRAY['pe_specific','leadership_effectiveness'],
  ARRAY['pe_firms','hr'],
  'direct',
  'new_buyer',
  4,
  'A newly strategic CPO at a PE-backed portco is a buyer Incompass hasn''t historically targeted — but should. As CPOs take ownership of leadership bench and retention, they need the tools to measure it. Incompass gives the strategic CPO the data infrastructure to own those conversations at the board level.',
  false
),

-- HEIDRICK & STRUGGLES TALENT LENS 2026
(
  'Demand for interim executives in PE-backed companies has risen significantly in 2026, with firms increasingly using interim placements as a diagnostic tool before committing to permanent leadership hires.',
  'Heidrick & Struggles 2026 Interim Talent Lens Survey, covering leadership placement trends across PE-backed and growth-stage companies.',
  'Heidrick & Struggles',
  '2026 Interim Talent Lens Survey',
  2026,
  ARRAY['pe_specific','leadership_effectiveness'],
  ARRAY['pe_firms'],
  'adjacent',
  'new_use_case',
  3,
  'Using interim executives as a diagnostic lens is a proxy for the absence of leadership assessment data. If PE firms had reliable talent intelligence upfront, they wouldn''t need interim placement to "test and learn." Incompass replaces the interim diagnostic with structured assessment — faster and cheaper than a 6-month interim engagement.',
  false
),

-- ADDITIONAL CROSS-SOURCE 2026 FINDINGS
(
  'Only 21.2% of organizations mandate goal-setting training for managers, and only 17.9% mandate feedback training — despite both being listed as core PM competencies.',
  '2026 Performance Management Report, Talent Strategy Group. Training mandate data across 250+ organizations.',
  'Talent Strategy Group',
  '2026 Performance Management Report',
  2026,
  ARRAY['measurement','leadership_effectiveness'],
  ARRAY['hr','c_suite'],
  'direct',
  'validates_product',
  4,
  'Fewer than 1 in 5 organizations train managers on feedback — the most fundamental leadership skill. This isn''t just a capability gap; it''s a structural one. Incompass addresses it at the process level: by standardizing how feedback is structured and collected, it reduces dependence on manager training that most organizations aren''t providing.',
  false
),
(
  '92.4% of organizations use ratings in performance reviews, yet only 63.6% provide any guidance on expected performance distributions — leaving calibration entirely to individual manager judgment.',
  '2026 Performance Management Report, Talent Strategy Group, 250+ organizations.',
  'Talent Strategy Group',
  '2026 Performance Management Report',
  2026,
  ARRAY['measurement','bias'],
  ARRAY['hr','c_suite'],
  'direct',
  'validates_product',
  5,
  'When 92% rate but only 64% provide distribution guidance, you get extreme grade inflation and inter-rater inconsistency — the exact problem Incompass''s calibration tools solve. This stat supports the argument that ratings without calibration infrastructure are worse than useless: they create false confidence in unfair data.',
  false
),
(
  'In 2026, AI is reshaping leadership expectations: effective leaders are now defined by their ability to apply judgment and accountability to AI-supported insights — a skill most current leaders have never been assessed for.',
  'Deloitte 2026 Global Human Capital Trends, supported by executive interviews across 50+ organizations. The "Human × Machine" leadership tipping point identified as the defining challenge of 2026.',
  'Deloitte',
  '2026 Global Human Capital Trends',
  2026,
  ARRAY['leadership_effectiveness','workforce_performance'],
  ARRAY['c_suite','pe_firms'],
  'adjacent',
  'new_use_case',
  4,
  'As AI redefines what good leadership looks like, traditional assessment methods become obsolete. Incompass is positioned to evolve its assessment framework to measure AI judgment capabilities — making this a product expansion opportunity, not just a market validation. First movers in AI-era leadership assessment own the next decade of the market.',
  false
),
(
  'Mercer''s Global Talent Trends 2026 — drawing from 12,000 executives, HR leaders, employees, and investors across 16 geographies — identifies workforce data utilization as the #1 unmet priority in talent strategy.',
  'Mercer Global Talent Trends 2026, surveying nearly 12,000 stakeholders across 16 industries and geographies.',
  'Mercer',
  'Global Talent Trends 2026',
  2026,
  ARRAY['measurement','workforce_performance'],
  ARRAY['hr','c_suite'],
  'direct',
  'validates_product',
  4,
  'Workforce data utilization being the top unmet priority across 12,000 stakeholders signals a massive market gap — organizations want data-driven talent decisions but lack the infrastructure to achieve them. Incompass is that infrastructure: structured calibration data, normalized ratings, and AI analysis that turns assessments into actionable intelligence.',
  false
),
(
  'Mercer 2026 finds organizations are reassessing their employee value proposition, with fair and transparent performance evaluation now ranking among the top three factors employees cite when choosing to stay or leave.',
  'Mercer Global Talent Trends 2026, employee retention drivers section across 16 geographies.',
  'Mercer',
  'Global Talent Trends 2026',
  2026,
  ARRAY['engagement','measurement'],
  ARRAY['c_suite','hr'],
  'direct',
  'validates_product',
  4,
  'When transparent performance evaluation is a top retention driver, Incompass is no longer just a compliance or efficiency tool — it''s a talent retention strategy. For CHROs facing pressure on attrition, this reframes Incompass as a direct lever on retention outcomes, not just process improvement.',
  false
),
(
  'The 2026 Deloitte Human Capital Trends report identifies "dynamic orchestration" — real-time capability management replacing static annual planning — as the defining workforce shift, with only 12% of organizations currently capable of it.',
  'Deloitte 2026 Global Human Capital Trends, 9,000+ respondents. Dynamic orchestration defined as the ability to redeploy talent in real time based on live performance and capability data.',
  'Deloitte',
  '2026 Global Human Capital Trends',
  2026,
  ARRAY['workforce_performance','measurement'],
  ARRAY['c_suite','pe_firms'],
  'direct',
  'white_space',
  4,
  'Only 12% of organizations can dynamically manage their talent in real time — and that requires exactly what Incompass provides: live performance data, calibrated ratings, and a clear picture of who can do what. Incompass is the data layer that enables dynamic orchestration, positioning it as infrastructure for the next era of workforce strategy.',
  false
);
